# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-SearchBox
version:      0.01
version_from: lib/Gtk2/Ex/SearchBox.pm
installdirs:  site
requires:
    Glib:                          0
    Gtk2:                          0
    Gtk2::Ex::PopupWindow:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
